export const letter1 = `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vel, repellendus soluta itaque iste ea aliquid asperiores ex est iure non labore eum eaque reprehenderit odio minima, harum nostrum. Odit nemo numquam distinctio ad ea porro praesentium excepturi. Tempore unde iure hic. Perferendis, aperiam quod similique a voluptas aliquid architecto, qui quasi rerum nostrum saepe placeat tenetur optio enim. Sed at amet quia libero non dolores ratione officia tempore. Libero dignissimos aut dolores error sequi vitae commodi amet nulla deserunt aliquid omnis possimus, odio sunt architecto quia esse accusamus. Corporis soluta temporibus voluptatum impedit ratione, quidem sequi repellendus sed nemo. Dolore perspiciatis praesentium nulla repellat placeat fuga architecto suscipit. Corporis labore quis inventore aperiam cupiditate atque corrupti molestias ad. Eligendi quas nihil, dicta in mollitia vel praesentium! Inventore quo, sunt exercitationem perspiciatis quam possimus voluptates dignissimos consectetur atque, eius, iure assumenda vel commodi harum rerum qui porro. Asperiores, omnis. Quae minus sunt nemo minima architecto repellendus eos magni doloribus sequi, commodi reiciendis cumque. Sunt tempore esse aliquid, praesentium quibusdam at fugit ipsum aliquam sapiente aut quidem. Vitae, atque ipsum facere sit aperiam beatae quo sunt modi, cum illum animi aliquam doloribus debitis earum molestiae dicta reprehenderit, ipsam placeat quas porro nesciunt iste deleniti nisi! Quo alias nobis, fuga dolores totam minus, dicta sapiente quod in earum aliquid animi laborum modi corrupti, culpa libero hic quisquam voluptatem id natus dolore. Quasi in veniam qui odit! Perspiciatis facere dignissimos quidem esse eaque accusantium. Odio molestias molestiae modi nulla obcaecati, quibusdam eum optio quod id hic quis illum et magnam. Perferendis quasi ab sunt, repellat officiis sint. Eos amet a molestias quasi sunt asperiores dicta fugit, est debitis dignissimos iste enim in odio et ab, labore maxime ipsum odit nemo saepe. Veritatis illum tempora expedita consequuntur deserunt. Obcaecati incidunt nulla amet, quidem omnis asperiores ut a. Dolorum maiores quod, vel voluptate ex deserunt vitae neque recusandae. Eius enim facilis repudiandae molestiae distinctio atque temporibus labore quos ad. Inventore vel officia iure. Fugiat ipsum ipsa voluptates. Qui, corporis debitis provident nesciunt nihil at libero iusto eaque recusandae quis possimus veritatis cumque eligendi reprehenderit accusamus, voluptatibus eum esse illum. Ipsam accusamus magnam totam amet deserunt earum molestias quia unde similique aut. Alias natus cupiditate accusamus. Quidem laboriosam blanditiis esse ipsa autem consectetur, est ea nobis quasi eveniet asperiores adipisci. Minus, accusamus pariatur beatae repellendus ex sequi commodi deleniti accusantium vitae unde veniam cupiditate, quisquam illum tempora incidunt. Ex necessitatibus magnam enim rem distinctio omnis dignissimos quis repudiandae, et animi! Ab rerum nam, placeat cupiditate repellat animi repudiandae voluptates consectetur fuga illum laborum, explicabo mollitia quisquam veritatis ex aut officia est unde id porro error recusandae. Ipsam omnis veritatis doloremque. Temporibus, reprehenderit illo aliquid vel, ullam ab unde laudantium eum quos pariatur assumenda fugiat aliquam. Vel maxime nam ullam eligendi veritatis. Explicabo quam reprehenderit porro modi sunt dolorem. Error reprehenderit tempora, laboriosam earum harum veritatis provident delectus et amet dolorem quas blanditiis excepturi debitis porro accusamus odio placeat deserunt iure voluptas expedita officia fugit aspernatur repellendus. Sapiente, nulla. Dolores excepturi aspernatur veniam exercitationem pariatur voluptas quis nostrum sequi. Culpa minima explicabo quod omnis facilis eveniet dolorum voluptatem repellendus id quas, ea ad earum, eaque nobis accusamus illum quia. Aliquid molestiae totam nobis iusto id natus eligendi, aliquam voluptates alias assumenda cumque veritatis impedit, recusandae quidem nulla voluptate maiores consequuntur repellat voluptatem perferendis cupiditate dolorum, velit iste blanditiis. Ex consequatur enim delectus fugit laboriosam quis saepe repellat veniam soluta tenetur sint voluptates quae ipsam, odio placeat dolorem recusandae unde dolorum aut quas sequi. Beatae porro minus facilis. `

export const letter2 =
  'abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ.ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ.ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. abcdefghijklmnopqrstuvwxyz. ABCDEFGHIJKLMNOPQRSTUVWXYZ. '

export const letter3 = `Once, Aunt Petunia, tired of Harry coming back from the barbers looking as though he hadnt been at all, had taken a pair of kitchen scissors and cut his hair so short he was almost bald except for his bangs, which she left to hide that horrible scar. Dudley had laughed himself silly at Harry, who spent a sleepless night imagining school the next day, where he was already laughed at for his baggy clothes and taped glasses. Next morning, however, he had gotten up to find his hair exactly as it had been before Aunt Petunia had sheared it off. He had been given a week in his cupboard for this, even though he had tried to explain that he couldnt explain how it had grown back so quickly. Another time, Aunt Petunia had been trying to force him into a revolting old sweater of Dudleys brown with orange puff balls. The harder she tried to pull it over his head, the smaller it seemed to become, until finally it might have fitted a hand puppet, but certainly wouldnt fit Harry. Aunt Petunia had decided it must have shrunk in the wash and, to his great relief, Harry wasnt punished. On the other hand, hed gotten into terrible trouble for being found on the roof of the school kitchens. Dudleys gang had been chasing him as usual when, as much to Harrys surprise as anyone elses, there he was sitting on the chimney. The Dursleys had received a very angry letter from Harrys headmistress telling them Harry had been climbing school buildings. But all hed tried to do as he shouted at Uncle Vernon through the locked door of his cupboard was jump behind the big trash cans outside the kitchen doors. Harry supposed that the wind must have caught him in midjump. But today, nothing was going to go wrong. It was even worth being with Dudley and Piers to be spending the day somewhere that wasnt school, his cupboard, or Mrs. Figgs cabbagesmelling living room. While he drove, Uncle Vernon complained to Aunt Petunia. He liked to complain about things people at work, Harry, the council, Harry, the bank, and Harry were just a few of his favorite subjects. This morning, it was motorcycles. roaring along like maniacs, the young hoodlums, he said, as a motorcycle overtook them.I had a dream about a motorcycle, said Harry, remembering suddenly. It was flying. Uncle Vernon nearly crashed into the car in front. He turned right around in his seat and yelled at Harry, his face like a gigantic beet with a mustache MOTORCYCLES DONT FLY! Dudley and Piers sniggered. I know they dont, said Harry. It was only a dream. But he wished he hadnt said anything. If there was one thing the Dursleys hated even more than his asking questions, it was his talking about anything acting in a way it shouldnt, no matter if it was in a dream or even a cartoon  they seemed to think he might get dangerous ideas. It was a very sunny Saturday and the zoo was crowded with families. The Dursleys bought Dudley and Piers large chocolate ice creams at the entrance and then, because the smiling lady in the van had asked Harry what he wanted before they could hurry him away, they bought him a cheap lemon ice pop. It wasnt bad, either, Harry thought, licking it as they watched a gorilla scratching its head who looked remarkably like Dudley, except that it wasnt blond. Harry had the best morning hed had in a long time. He was careful to walk a little way apart from the Dursleys so that Dudley and Piers, who were starting to get bored with the animals by lunchtime, wouldnt fall back on their favorite hobby of hitting him. They ate in the zoo restaurant, and when Dudley had a tantrum because his knickerbocker glory didnt have enough ice cream on top, Uncle Vernon bought him another one and Harry was allowed to finish the first. Harry felt, afterward, that he should have known it was all too good to last. After lunch they went to the reptile house. It was cool and dark in there, with lit windows all along the walls. Behind the glass, all sorts of lizards and snakes were crawling and slithering over bits of wood and stone. Dudley and Piers wanted to see huge, poisonous cobras and thick, mancrushing pythons. Dudley quickly found the largest snake in the place. It could have wrapped its body twice around Uncle Vernons car and crushed it into a trash can  but at the moment it didnt look in the mood. In fact, it was fast asleep. Dudley stood with his nose pressed against the glass, staring at the glistening brown coils. Make it move, he whined at his father. Uncle Vernon tapped on the glass, but the snake didnt budge. Do it again, Dudley ordered. Uncle Vernon rapped the glass smartly with his knuckles, but the snake just snoozed on. This is boring, Dudley moaned. He shuffled away. Harry moved in front of the tank and looked intently at the snake. He wouldnt have been surprised if it had died of boredom itself  no company except stupid people drumming their fingers on the glass trying to disturb it all day long. It was worse than having a cupboard as a bedroom, where the only visitor was Aunt Petunia hammering on the door to wake you up at least he got to visit the rest of the house. The snake suddenly opened its beady eyes. Slowly, very slowly, it raised its head until its eyes were on a level with Harrys. It winked. Harry stared. Then he looked quickly around to see if anyone was watching. They werent. He looked back at the snake and winked, too. The snake jerked its head toward Uncle Vernon and Dudley, then raised its eyes to the ceiling. It gave Harry a look that said quite plainlyI get that all the time. I know, Harry murmured through the glass, though he wasnt sure the snake could hear him. It must be really annoying. The snake nodded vigorously. Where do you come from, anyway? Harry asked. The snake jabbed its tail at a little sign next to the glass. Harry peered at it. Boa Constrictor, Brazil. The boa constrictor jabbed its tail at the sign again and Harry read on This specimen was bred in the zoo. Oh, I see  so youve never been to Brazil? As the snake shook its head, a deafening shout behind Harry made both of them jump. Dudley came waddling toward them as fast as he could. `

export const letter4 = `"Scarlett, when you are fortyfive, perhaps you will know what I'm talking about and then perhaps you, too, will be tired of imitation gentry and shoddy manners and cheap emotions. But I doubt it. I think you'll always be more attracted by glister than by gold. Anyway, I can't wait that long to see. And I have no desire to wait. It just doesn't interest me. I'm going to hunt in old towns and old countries where some of the old times must still linger. I'm that sentimental. Atlanta's too raw for me, too new."  "Stop," she said suddenly. She had hardly heard anything he had said. Certainly her mind had not taken it in. But she knew she could no longer endure with any fortitude the sound of his voice when there was no love in it  He paused and looked at her quizzically.  "Well, you get my meaning, don't you?" he questioned, rising to his feet.  She threw out her hands to him, palms up, in the ageold gesture of appeal and her heart, again, was in her face.  "No," she cried. "All I know is that you do not love me and you are going away! Oh, my darling, if you go, what shall I do?"  For a moment he hesitated as if debating whether a kind lie were kinder in the long run than the truth. Then he shrugged.  "Scarlett, I was never one to patiently pick up broken fragments and glue them together and tell myself that the mended whole was as good as new. What is broken is broken and I'd rather remember it as it was at its best than mend it and see the broken places as long as I lived. Perhaps, if I were younger " he sighed. "But I'm too old to believe in such sentimentalities as clean slates and starting all over. I'm too old to shoulder the burden of constant lies that go with living in polite disillusionment. I couldn't live with you and lie to you and I certainly couldn't lie to myself. I can't even lie to you now. I wish I could care what you do or where you go, but I can't."  He drew a short breath and said lightly but softly  "My dear, I don't give a damn."  She silently watched him go up the stairs, feeling that she would strangle at the pain in her throat. With the sound of his feet dying away in the upper hall was dying the last thing in the world that mattered. She knew now that there was no appeal of emotion or reason which would turn that cool brain from its verdict. She knew now that he had meant every word he said, lightly though some of them had been spoken. She knew because she sensed in him something strong, unyielding, implacable all the qualities she had looked for in Ashley and never found.  She had never understood either of the men she had loved and so she had lost them both. Now, she had a fumbling knowledge that, had she ever understood Ashley, she would never have loved him had she ever understood Rhett, she would never have lost him. She wondered forlornly if she had ever really understood anyone in the world.  There was a merciful dullness in her mind now, a dullness that she knew from long experience would soon give way to sharp pain, even as severed tissues, shocked by the surgeon's knife, have a brief instant of insensibility before their agony begins.  "I won't think of it now," she thought grimly, summoning up her old charm. "I'll go crazy if I think about losing him now. I'll think of it tomorrow."  "But," cried her heart, casting aside the charm and beginning to ache, "I can't let him go! There must be some way!"  "I won't think of it now," she said again, aloud, trying to push her misery to the back of her mind, trying to find some bulwark against the rising tide of pain. "I'll why, I'll go home to Tara tomorrow," and her spirits lifted faintly.  She had gone back to Tara once in fear and defeat and she had emerged from its sheltering walls strong and armed for victory. What she had done once, somehow please God, she could do again! How, she did not know. She did not want to think of that now. All she wanted was a breathing space in which to hurt, a quiet place to lick her wounds, a haven in which to plan her campaign. She thought of Tara and it was as if a gentle cool hand were stealing over her heart. She could see the white house gleaming welcome to her through the reddening autumn leaves, feel the quiet hush of the country twilight coming down over her like a benediction, feel the dews falling on the acres of green bushes starredwith fleecy white, see the raw color of the red earth and the dismal dark beauty of the pines on the rolling hills.  She felt vaguely comforted, strengthened by the picture, and some of her hurt and frantic regret was pushed from the top of her mind. She stood for a moment remembering small things, the avenue of dark cedars leading to Tara, the banks of cape jessamine bushes, vivid green against the white walls, the fluttering white curtains. And Mammy would be there. Suddenly she wanted Mammy desperately, as she had wanted her when she was a little girl, wanted the broad bosom on which to lay her head, the gnarled black hand on her hair. Mammy, the last link with the old days.  With the spirit of her people who would not know defeat, even when it stared them in the face, she raised her chin. She could get Rhett back. She knew she could. There had never been a man she couldn't get, once she set her mind upon him.  "I'll think of it all tomorrow, at Tara. I can stand it then. Tomorrow, I'll think of some way to get him back. After all, tomorrow is another day. `

export const KEYS = [
  ' ',
  'q',
  'w',
  'e',
  'r',
  't',
  'y',
  'u',
  'i',
  'o',
  'p',
  'a',
  's',
  'd',
  'f',
  'g',
  'h',
  'j',
  'k',
  'l',
  'z',
  'x',
  'c',
  'v',
  'b',
  'n',
  'm',
  'Q',
  'W',
  'E',
  'R',
  'T',
  'Y',
  'U',
  'I',
  'O',
  'P',
  'A',
  'S',
  'D',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  'Z',
  'X',
  'C',
  'V',
  'B',
  'N',
  'M',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '0',
  '!',
  '@',
  '#',
  '$',
  '%',
  '^',
  '&',
  '*',
  '(',
  ')',
  '-',
  '_',
  '=',
  '+',
  '\\',
  '|',
  '[',
  ']',
  '{',
  '}',
  ';',
  ':',
  "'",
  '"',
  '/',
  '?',
  '.',
  '>',
  ',',
  '<',
]

export const capitals = [
  'Q',
  'W',
  'E',
  'R',
  'T',
  'Y',
  'U',
  'I',
  'O',
  'P',
  'A',
  'S',
  'D',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  'Z',
  'X',
  'C',
  'V',
  'B',
  'N',
  'M',
]

export const notCapitals = [
  'q',
  'w',
  'e',
  'r',
  't',
  'y',
  'u',
  'i',
  'o',
  'p',
  'a',
  's',
  'd',
  'f',
  'g',
  'h',
  'j',
  'k',
  'l',
  'z',
  'x',
  'c',
  'v',
  'b',
  'n',
  'm',
]

export const s500 =
  'Once Aunt Petunia tired of Harry. Coming back from the barbers looking as though he hadnt been at all. Had taken a pair of kitchen scissors. Afterwards cut his hair so short he was almost bald except for his bangs. Which she left to hide that horrible scar. Dudley had laughed himself silly at Harry. Who spent a sleepless night imagining school the next day where he was already laughed at for his baggy clothes and taped glasses. Happiest morning however. He had gotten up to find his hair exactly as it had been before Aunt Petunia had sheared it off. He had been given a week in his cupboard for this. '
